name: "🐛 Bug Report"
description: Create a new ticket for a bug.
title: "🐛 [BUG] - <title>"
labels: [
"bug"
]
body:
- type: textarea
  id: description
  attributes:
    label: "Description"
    description: Please enter an explicit description of your issue, including screenshots if applicable.
    placeholder: Short and explicit description of your incident...
  validations:
    required: true
- type: textarea
  id: reprod
  attributes:
    label: "Reproduction steps"
    description: Please enter an explicit description of your issue.
    value: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
    render: bash
  validations:
    required: true
- type: input
  id: kit-version
  attributes:
    label: "Kit Version"
    description: What version of the kit are you using?
    placeholder: "1.3.0"
  validations:
    required: true