AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Get Privy Social Identifiers

  This lambda function is used to get the social identifiers for a given embedded wallet address.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    LoggingConfig:
      LogFormat: JSON
    Environment:
      Variables:
        PRIVY_APP_ID: !Ref PrivyAppId
        PRIVY_APP_SECRET: !Ref PrivyAppSecret

Resources:
  GetSocialIdentifiersFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: index.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
      - arm64
      Events:
        GetSocialIdentifiers:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /get-social-identifiers
            Method: get
            Auth:
              ApiKeyRequired: true
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - index.ts

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub ${AWS::StackName}-ApiKey
      Description: API Key for accessing the API
      Enabled: true
      StageKeys:
        - RestApiId: !Ref ServerlessRestApi
          StageName: Prod
      UsagePlan:
        CreateUsagePlan: PER_REQUEST
        Quota:
          Limit: 5000
          Period: MONTH
        Throttle:
          BurstLimit: 200
          RateLimit: 100

Parameters:
  PrivyAppId:
    Type: String
    Description: Privy App ID
    NoEcho: true
  PrivyAppSecret:
    Type: String
    Description: Privy App Secret
    NoEcho: true

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetSocialIdentifiersApi:
    Description: API Gateway endpoint URL for Prod stage for Get Social Identifiers
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get-social-identifiers"
  GetSocialIdentifiersFunction:
    Description: Get Social Identifiers Lambda Function ARN
    Value: !GetAtt GetSocialIdentifiersFunction.Arn
  GetSocialIdentifiersFunctionIamRole:
    Description: Implicit IAM Role created for Get Social Identifiers
    Value: !GetAtt GetSocialIdentifiersFunctionRole.Arn
  ApiKey:
    Description: API Key for accessing the API
    Value: !Ref ApiKey
